### ISSUE TITLE
Beschaffung Rechner

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#12]
Mögliche Referenz: Rechner des Interactive Scape

**Silent PC 2060** -> Preis laut InteractiveScape-Angebot von hyTracks: 2160,- €

» CPU: Intel Core i7
» 16 GB DDR4 RAM
» 250 GB SSD Samsung M.2 970 Evo NVMe
» GPU: NVIDIA GeForce RTX 2070 mit 8GB RAM 2xHDMI 2.0 » Displayport, 4k@60Hz
» 2x Gigabit LAN
» WLAN: 802.11ac
» SSD und M.2
» USB: 3.0, 3.1
» Bluetooth 5
» Abmessungen: 225x203x128 mm
» Externes Netzteil
» Windows 10 Pro 64bit

Edit: https://www.interactive-scape.com/scape-movable-55-de.html

---

[Dell Tower.pdf](https://github.com/Lwinkeler/Q100-AB2-qScope/files/6277083/Dell.Tower.pdf)
Vgl. Beschaffung der Kollegen aus HH..

**Comment by dunland** [comment]
hier noch ein Vorschlag von Torben:

https://www.spo-comm.de/produkte/alle-mini-pcs/kumo-ryzen#fv-config-sections--outer-container

**Comment by dunland** [comment]
> hier noch ein Vorschlag von Torben:
> 
> https://www.spo-comm.de/produkte/alle-mini-pcs/kumo-ryzen#fv-config-sections--outer-container
> 
> Torben:
> 
> > Haben da auch noch ein paar andere Rechner.. keine Ahnung ob die was können fand es wegen der Ports @4k interessant

hierzu eine kleine Recherche:
der [Kumo Ryzen](https://www.spo-comm.de/produkte/alle-mini-pcs/kumo-ryzen#fv-config-sections--outer-container) lässt ich mit AMD® Ryzen **V1605B oder V1807B CPU** liefern, beide haben maximal 4 Kerne, womit diese Ausführung raus fällt.

der [Core 2](https://www.spo-comm.de/produkte/alle-mini-pcs/core-2#dkv-technical) hingegen könnte eine echte Option darstellen mit folgenden Specs:

```
    CPU: Intel® Core i7-9700, 8 x 3,0 GHz
    RAM: 16384 MB SO-DDR4
    Grafikkarte: Intel® GMA HD
    HDD: 128 GB SATA SSD
    Betriebssystem: keins / none
    Zubehör: spo-comm Wireless Tastatur 7 DE
    Zubehör: Monitorkabel DisplayPort auf DisplayPort 2m
    Garantie: spo-book Standardgarantie 2 Jahre
```

> Ihr Preis für das konfigurierte System beträgt 744,00 € zzgl. MwSt. und Versandkosten.

Damit könnten wir einen Sieger haben..

**Comment by Lwinkeler** [comment]
Hört sich ja wirklich nach einem Preisknaller an - Rabatte Rabatte Rabatte. Wo ein Haken sein könnte wüsste ich für meinen Teil nun auch nicht.

> Der Prozessor ist 8. Generation ‒ mittlerweile gibt es schon die 12. Generation auf dem Markt. Was das genau für ein Unterschied ist, kann ich nicht einschätzen.
Lässt sich das (mit geringem Aufwand) herausfinden? Vielleicht liegts ja tatsächlich daran.

**Comment by dunland** [comment]
> Lässt sich das (mit geringem Aufwand) herausfinden? Vielleicht liegts ja tatsächlich daran.

Mail an Lehmkuhl ist raus ‒ vielleicht weiß der was. Sonst recherchiere ich auch nochmal.

**Comment by dunland** [comment]
wird hier geschlossen, weil GK und TS sich drum kümmern
