### ISSUE TITLE
unterste Reihe ist Slider Control

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#21]
- Auswahl der zu bespielenden Parameter via Slider wird durch letzte Reihe bestimmt
- → 11 Parameter pro Slider?
- wo sollen Parameter(kategorien) hinterlegt sein? Wie dynamisch muss das ausgestaltet sein?

**Comment by dunland** [comment]
siehe https://github.com/dunland/q100_viz/commit/ee15db29229ebb2a887880911ee44e57fa30f88e ✓
slider control in unterster Grid-Reihe ist jetzt realisiert über ein `slider_handle` im `TuiMode`. So können die zu bearbeitenden Parameter in eine Liste eingetragen werden und [später](https://github.com/dunland/q100_viz/commit/ee15db29229ebb2a887880911ee44e57fa30f88e#diff-5a544302d16fafdac3e329890901d27faedf62804c89015767bc5e9cd6cffbbaR58) Funktionen zugewiesen bekommen.

TODO:
- [ ] besondere Anzeigeweise der Projektion in diesen Feldern @dunland 
- [ ] Anzeige der bisher implementierten Parameter `'year', 'foerderung', 'CO2-Preis', 'CO2-emissions', 'Technologie', 'investment', 'Anschluss'` im infoscreen @cqx931

**Comment by cqx931** [comment]
https://github.com/cqx931/q100_info/commit/982002c4dc165d65ae8a03a2b3ddb08295e01ca3

**Comment by dunland** [comment]
@dunland :
- [ ] highlight fields differently according to function
- [ ] highlight slider accordingly
- [ ] display function text on screen

**Comment by dunland** [comment]
- [ ] place the colored rectangle at exact position of slider
- [ ] multiple sliders: 
    - [ ] which one affects which?
    - [ ] create multiple colored rectangles
- [ ] place function text or icon at an approrpiate position
- [ ] what to do if multiple slider controls surfaces are selected?
