### ISSUE TITLE
Confidence Interval

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#22]
Confidence-Interval für die Erkennung der tags: Eine Reaktion im Frontend soll nur stattfinden, wenn sich das tag in den letzten ~2s nicht geändert hat.

Hintergrund:
Aufgrund ungleichmäßiger Ausleuchtung des Tisches und einem minimalem Spielraum in der Platzierung der tokens innerhalb der Zellen ist die Tag-Erkennung immer bei einigen Steinen etwas wackelig. Das äußert sich darin, dass sich die IDs im Sub-Sekunden-Bereich stetig ändern. Mit einem Confidence Interval könnte man sicherstellen, dass eine ID nur erfasst wird, wenn sie >2s stabil geblieben ist.

**Comment by cqx931** [comment]
cspy/setting/citycopy.json -> interval 
q100_viz : nur Datei ändern wenn sie >2s stabil geblieben ist.

**Comment by dunland** [comment]
Erstmal nicht mehr so wichtig, da es derzeit unter Nutzung aller Parameter stabil läuft.

**Comment by dunland** [comment]
should be fine for now after https://github.com/dunland/cspy/commit/9a3fa76262be9c9a893451bf57a5414cecd84a8b !
