### ISSUE TITLE
slider production

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#32]
Seems like we need four sliders located at one side of the table. Since they should all be about the same size, we have to remake all of them.
![slider5-1](https://user-images.githubusercontent.com/23742320/165715437-20086ed2-61ad-43c8-a3b7-f6e164794b71.png)

This is the layout for the sliders. @kazux2 can you create this file using Adobe Illustrator? You can make it based on the file slider4-1.svg. It is almost what we need, except that I think the slider length could have the size of 9 grid cells and, hence, a symmetric distribution over the whole grid part.

I will order the following material:
- 2 x 3 mm x 40 cm x 28 cm white opaque for the creation of 2 half-grids (dimensions 38.6 cm x 24.55 cm)
- 2 x 3 mm x 38.6 cm x 24.6 cm transparent as half-grid bottom side
- 4 x 3 mm x 40 cm x 15 cm white opaque for the creation of 4 slider tops (dimensions 38.6 cm x 13.8 mm)
- 4 x 1.5 mm x 40 cm x 15 cm transparent for the creation of 4 slider middle-parts (dimensions 38.6 cm x 13.8 mm)
- 4 x 1.5 mm x 386 mm x 138 transparent mm serving directly as 4 slider bottom sides

**Comment by kazux2** [comment]
- [ ] 2 x 3 mm x 40 cm x 28 cm white opaque for the creation of 2 half-grids (dimensions 38.6 cm x 24.55 cm)
- [ ] 2 x 3 mm x 38.6 cm x 24.6 cm transparent as half-grid bottom side
- [ ] 4 x 3 mm x 40 cm x 15 cm white opaque for the creation of 4 slider tops (dimensions 38.6 cm x 13.8 mm)
- [ ] 4 x 1.5 mm x 40 cm x 15 cm transparent for the creation of 4 slider middle-parts (dimensions 38.6 cm x 13.8 mm)
- [ ] 4 x 1.5 mm x 386 mm x 138 transparent mm serving directly as 4 slider bottom sides
