### ISSUE TITLE
check all units! @lwinkeler @dunland sind die Einheiten in den Graphen alle korrekt?

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/qScope_frontend#40]
# Grafische Darstellung der Infoscreens

## CO2-Emissionen 
- aktuelle Darstellung: 
 - Einzelhaushalte: g CO2-eq (ca. im Bereich 100.000-900.000)
 - Gruppierte Darstellung: kg/kWh -> kWh Wärme/Strom/Gesamtenergieverbrauch? Welche Daten werden hier genutzt? (es werden nur emissionen exportiert..)
 - Kumulierte Darstellung Quartier (*nicht!* **A**kkumuliert): gCO2*1e10 (hier fehlt der eq-Zusatz)

- vgl. 7,75 Tonnen CO2-eq / Jahr DE-durchschnitt (Kurve einblenden zur Übersicht?)

- Die Angaben erfolgen in g, sollten aber für die Darstellung mit den Haushalten in Tonnen umgerechnet werden; könnte das Verständnis verbessern

## Energiekosten
- Allgemein: power/Strom price & energy price durcheinander gebracht!!
- Hausspezifisch:
  - Die Angaben hier sind **nicht** pro kWh! Das sind bereits die berechneten absoluten Ausgaben in € (nicht ct), welche die entsprechenden Haushalte entrichten (pro Monat)
  

## Weiterführende Auffälligkeiten: 

- kein Haushalt kommt auf 0-Emissionen (obwohl im Jahr 2045 auch Strom bei 0-Emissionen ist)
- Simulationszeitraum? 
  - 2020-2030? 2020-2040? 2020-2050?

**Comment by lwinkeler** [comment]
- [ ] Absprache der o.g. Punkte zwischen @dunland & @lwinkeler

**Comment by dunland** [comment]
hier nochmal aus unserem Gespräch:

- individuelle Energiekosten: spezi. Verbrauch Wärme + Strom * Kosten Energiequelle → €/Monat
- Energiekosten Quartier: "Strompreis" und [ct/kWh]
- Emissionen individuell: Gesamtemissionen [g/Monat] → [t/Monat] oder gar [t/Jahr]?
- Durchschnittskurve Individ. Emissionen
- kumulierte Gesamtemissionen des Quartiers: CO2-Equivalänte

**Comment by lwinkeler** [comment]
Sind hier noch offene Punkte? Ansonsten: Kann das issue geschlossen werden?

**Comment by dunland** [comment]
Sind die Einheiten denn nun alle so richtig?


![CO2_emissions_7 57](https://user-images.githubusercontent.com/23742320/192967295-e91fb7a2-4958-4439-b109-5727a29d9d47.png)
![CO2_emissions_groups](https://user-images.githubusercontent.com/23742320/192967302-3f00654f-a02b-4558-b693-0ebaf851730a.png)
![CO2_emissions_neighborhood](https://user-images.githubusercontent.com/23742320/192967308-ae3c8700-7301-45a0-a2f8-bc5d5701812b.png)
![energy_prices_7 54](https://user-images.githubusercontent.com/23742320/192967327-5fcaf00d-eb12-4aad-b5a6-2854e78dd2e7.png)
![energy_prices_groups](https://user-images.githubusercontent.com/23742320/192967332-017820e6-9e0a-436a-859e-6f1f86da1cc0.png)
![energy_prices_total](https://user-images.githubusercontent.com/23742320/192967334-414a1e4c-9669-46ae-89c1-867a283b9fee.png)

**Comment by lwinkeler** [comment]
Folgende Punkte hätte ich anzumerken:

- [ ] Darstellung der Emissionen in t (statt g oder kg) bzw. in t/Monat
- [ ] Absprache mit R&E, welches die gewünschte Einheit ist: Emissionen/Monat oder Emissionen/Jahr? Hängt auch von den zusätzlich zum qScope bereitgestellten Informationen ab!
- [ ] Einige Jahreszahlen treten in der Darstellung in 2,5er Schritten auf. Mein Vorschlag wäre es jährliche / alle zwei Jahre / alle 5 Jahre darzustellen? Bestenfalls plot-übergreifen, also einheitlich.
- [ ] ersichtlich in https://github.com/quarree100/q100_abm/issues/76 : Zur Vergleichbarkeit der einzelnen Häuser miteinander sind die gleichen Skalen auf der y-Achse hilfreich. Dem gegenüber steht das Problem, dass möglicherweise ein Graph mit hohen Werten (bspw. MFH) die Skala vorgibt und die Kurve des Graphen mit niedrigen Werten (bspw. EFH) zu klein dargestellt wird. Was meinst du @dunland ?

**Comment by dunland** [comment]
Graphen sehen nun so aus:

![image](https://user-images.githubusercontent.com/23742320/199254613-0252f767-71aa-4df6-9f8c-acc97532b6d8.png)
![image](https://user-images.githubusercontent.com/23742320/199254702-3648475f-9102-46a0-a48e-46dbe61847e3.png)
![image](https://user-images.githubusercontent.com/23742320/199254736-a55604ff-0b2e-43ed-bcba-035b4dcfed61.png)
![image](https://user-images.githubusercontent.com/23742320/199254752-d33aff92-1cc4-4297-9dfc-4c91a8a5c73a.png)

habe die Y-Achsenbeschriftungen und die Titel geändert. Bitte überprüfen! @lwinkeler
vielleicht geben wir das auch nochmal DFuh zum drüber schauen, wenn wir hier fertig sind?

**Comment by lwinkeler** [comment]
- Top soweit; siehe Präsenzabsprache 02.11.2022
- Ich würde es, sobald es Ende der Woche mit den letzten Änderungen abgestimmt ist, nochmal mit einem ausgewählten Personenkreis, die nicht im MediasInRes-Team sind, besprechen.
