### ISSUE TITLE
historische Energiepreise zu Simulationsergebnissen hinzufügen

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#42]
- [x] historische Energiepreise sollen **zumindest als Backup** für Rückfragen zur Verfügung stehen! Kür: historische Daten an Individualgraphen voranstellen

_Originally posted by @dunland in https://github.com/quarree100/qScope_frontend/issues/39#issuecomment-1291968817_

**Comment by dunland** [comment]
erste Resultate:

Energy_expenses_hh (Ausgaben eines Privathaushaltes für Energie (ohne Kraftstoff) in Deutschland in den Jahren 2000 bis 2020 (in Euro pro Monat)) allein:

![energy_expenses_hh](https://user-images.githubusercontent.com/23742320/199467046-5fda246d-f451-4d23-a527-a51cce3316a0.png)
Soll dieser Graph dann jeweils vor die **individuellen Energiekosten** gehängt werden?

---
und hier die Energiepreise (Deutschland?) an die Simulationsergebnisse vorangehängt:
![energy_prices_hh](https://user-images.githubusercontent.com/23742320/199467052-71f5449c-ccdd-4597-b17d-7110f3a82ced.png)
eine starke Diskrepanz zwischen historischen Daten und Annahme zur Beginn der Simulation lässt sich in den Strompreisen erkennen. Lässt sich das schnell anpassen? Auch die Gaspreise sind etwas zu gering.

**Comment by lwinkeler** [comment]
zu Bild 1: 
- Die Einheiten der y-AChse sind €/Monat (s. Bildtitel oben)

> Soll dieser Graph dann jeweils vor die individuellen Energiekosten gehängt werden?
- ja im Prinzip haben wir da die zwei Optionen, dass wir das direkt davor hängen (1) oder das ebenfalls als "Backup-Folie" im Hintergrund halten (2). 

> und hier die Energiepreise (Deutschland?) an die Simulationsergebnisse vorangehängt:
- ja, das sind die Energiepreise für Haushalte in Deutschland.

> eine starke Diskrepanz zwischen historischen Daten und Annahme zur Beginn der Simulation lässt sich in den Strompreisen erkennen. Lässt sich das schnell anpassen? Auch die Gaspreise sind etwas zu gering.
- Befindet sich in Arbeit in Form der Überarbeitung der Energiepreisentwicklung

**Comment by dunland** [comment]
noch was: die historischen Daten gehen meist bis 2021, die Simulation fängt schon bei 2020 an. → für 2020 und 2021 nehme ich dann die historischen Daten?

**Comment by lwinkeler** [comment]
> noch was: die historischen Daten gehen meist bis 2021, die Simulation fängt schon bei 2020 an. → für 2020 und 2021 nehme ich dann die historischen Daten?

Nach erfolgreicher Überarbeitung der Energiepreisentwicklung dürften die Daten nicht mehr allzu weit auseinander liegen. Trotzdem guter Punkt! Ich würde die historischen Daten bis (einschließlich) 2019 nehmen und für 2020 die Simulationsdaten, damit das einheitlich ist.

**Comment by dunland** [comment]
Ok, kann ich auch so anpassen. Ist es denn nicht besser, die historischen Daten so weit zu verwenden, wie wir sie zur Verfügung haben? Das sind ja nunmal die Realdaten!

**Comment by lwinkeler** [comment]
Jaein :)

Ende 2021 gab es bereits einen enormen Anstieg der Realdaten. Für das Modell gehen wir aber, egal wie gut wir die Energiepreisentwicklung jetzt noch ausarbeiten, von einem einigermaßen beruhigten Markt aus.
Das Problem würde sein, dass wir diesen krassen Anstieg hätten (der eigentlich in die aktuellen Preise münden würde) und die Modelldaten das dann wieder zu Fall bringen würden..

Letztlich ist beides eine Frage der Argumentation. Ich würde mich für die Variante "wir simulieren einen beruhigten Energiemarkt wie er vor zwei Jahren existierte, da wir eine Annahme für die Simulation treffen mussten".

**Comment by dunland** [comment]
> zu Bild 1:
> 
>     * Die Einheiten der y-AChse sind €/Monat (s. Bildtitel oben)
> 
> 
> > Soll dieser Graph dann jeweils vor die individuellen Energiekosten gehängt werden?
> 
>     * ja im Prinzip haben wir da die zwei Optionen, dass wir das direkt davor hängen (1) oder das ebenfalls als "Backup-Folie" im Hintergrund halten (2).
> 

da haben wir ein Problem: Die historischen Daten sind ja aufgeschlüsselt als Strom, Gas, Öl; wir arbeiten hingegen mit "Strom" und "Wärme".

"Gas+Öl = Wärme" wäre eine Annahme, die nur für Haushalte mit diesen Energieträgern gilt.....
ich könnte sowas machen wie

``` python
if building.energy_source == 'gas':
    building.heat = data.gas
elif building.energy_source == 'oil':
    # undsoweiter
```

... ?

**Comment by dunland** [comment]
richtig! Ich bin total durcheinander.
Dennoch: (Wie) dröseln wir dann die energy-expenses_hh auf Wärme+Strom auf?

**Comment by lwinkeler** [comment]
hehe, ja guck an. Bei mir läufts auch etwas unrund im Oberstübchen.. Dachte irgendwie, dass das ebenfalls nur die Gesamtkurve der Energiekosten wäre.

- [ ] Ich überlege mir was!

**Comment by dunland** [comment]
![image](https://user-images.githubusercontent.com/23742320/199742019-d4ec8e56-6f03-4379-adb0-5cc8fc7cedeb.png)


erstmal sähe das so aus..

**Comment by lwinkeler** [comment]
Violà!
https://de.statista.com/statistik/daten/studie/166439/umfrage/ausgaben-der-haushalte-fuer-raumwaerme-und-warmwasser-seit-1990/
(spannenderweise sagt der Link `...-seit-1990` aber es ist von 2000-2020)

Wollte erst noch nach der gleichen Statistik für Strom suchen, die es auf den ersten Blick nicht gibt, aber das reicht uns ja schon. Den Stromanteil können wir dann (grob) rausrechnen.

**Comment by dunland** [comment]
:+1: :+1: :+1:  hast du da einen Account? Kannst du das runterladen?

**Comment by lwinkeler** [comment]
Erledigt und angepasst.
siehe Seafile `Q-Scope_data/data_pre-simulation/energy-expenses_hh_2000-2020.csv` Habe die Datei erweitert mit den entsprechenden Werten.

Die Uni hat Zugang zu fast allen Daten von Statista. Sobald du im eduroam bist, hast du auch ohne Anmeldung Zugriff. Im Homeoffice einfach den VPN einschalten.

**Comment by dunland** [comment]
![image](https://user-images.githubusercontent.com/23742320/199750124-1e368142-ea59-4386-a838-f5e69b825a1f.png)

getting there!

**Comment by dunland** [comment]
...._tschakkaaaaa!!!_

![image](https://user-images.githubusercontent.com/23742320/199754448-e88ee883-487f-4f42-8490-30d9caca1b0c.png)

**Comment by lwinkeler** [comment]
N1!!

**Comment by dunland** [comment]
jetzt auch in Graph für "generelle Energiekosten"!
![energy_prices_total](https://user-images.githubusercontent.com/23742320/200171381-10f110f0-3d6f-4c22-8002-b55e0314da6b.png)
